### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by dagnelies** [dagnelies/ractive-codemirror#2]
Hi, please do not use the latest version. It is broken because of https://github.com/ractivejs/ractive/issues/1988
Until the latter one is fixed, please use the previous version.

**Comment by zaus** [comment]
Is this why you can't attach events to the component?

Clarification:  my mouseup and keyup events aren't firing:

```
<codemirror mode=... on-mouseup="dosomething" on-keyup="dosomething" />
```

**Comment by dagnelies** [comment]
Hi,
nope, event bindings are simply not yet implemented. Pull requests are welcome.
